### ISSUE TITLE
课程回放某些视频切片请求返回503 Service Unavaliable导致不能正常播放

### ISSUE THREAD

**Issue by MUTED64** [brfish/xd-no-flash-plz#5]
可参考：http://newesxidian.chaoxing.com/live/viewNewCourseLive1?isStudent=1&liveId=10626948
在获取 `playback.m3u8` 中第三个切片 `3_401078941_1622478057_1622478055.ts` 的时候服务器一直返回503导致视频卡住播放不了。如下图：
![image](https://user-images.githubusercontent.com/50164562/120957281-f6cbdd00-c787-11eb-95d3-d88db3ce80be.png)
其它课程也有类似问题。

尝试去手动请求的503的链接进行测试的时候发现录播切片的命名格式是 `切片索引_不确定是什么的字段_结束时间戳_开始时间戳.ts`，其中每个相邻ts切片中那个不确定是什么的字段都相差60（迷惑了）。手动修改后三个字段的任意一个都会略微改变获取到的视频切片的长度，而且有概率避免503错误，成功请求到ts文件。

~~昨天试着fork了一份想修一下，后来发现无从下手放弃了 orz~~
推测应该是学校后端视频切割的问题，有什么可能能够修复这个吗

**Comment by brfish** [comment]
确实有这个问题，发现损坏的片段比以往使用的时候要多很多。使用的 `videojs` 播放器在遇到无法请求的切片时会不停地尝试重新获取播放列表，导致直接卡死。切片的时长基本为 2s （结尾片段可能为 1s ），所以现在的想法是直接简单粗暴地跳过这些损坏切片，应该不会很影响观看
`videojs` 没有提供直接控制跳过损坏切片的选项，也没找到什么好方法... 
所以现在大概就是打算监视 `retryplaylist` 事件以及直接修改 `tech().vhs.selectPlaylist.segments` ，具体还要再测试一下

**Comment by MUTED64** [comment]
手动测试的时候发现在视频切片命名的第二个字段的数值+1或者+2有很大概率可以请求到视频切片，而且不会对视频长度有太大的影响，基本也就是差个几毫秒这样。
或许可以有监视到损坏的切片以后把第二个字段的数值进行自增之后再拼接回去发包的这种逻辑，播放体验应该会更好一些，不过没想到具体要怎么实现，感觉可能不太好弄…前端感觉也不是太好控制`videojs`发送请求的逻辑
~~好想控诉学校啊~~

**Comment by brfish** [comment]
PR #6 
现在可以跳掉大部分的损坏切片，结尾处的还有问题可能导致播放列表失效
